name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++ make libglfw3-dev libassimp-dev libglm-dev

    - name: Compile
      run: |
        num_cores=$(nproc)
        make -j$num_cores

    - name: Verify Executable
      run: |
        if [ ! -f ./main ]; then
          echo "Error: The expected executable 'main' was not found!"
          exit 1
        fi

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: main-executable
        path: ./main
